server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petropolis?createDatabaseIfNotExist=true&characterEncoding=utf-8
    username: root
    password: petropolis
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      hdbm2ddl:
        create_namespaces: true
        auto: update
      ddl-auto: update
    show-sql: true
    format-sql: true
    generate-ddl: true

