server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petropolis?createDatabaseIfNotExist=true&characterEncoding=utf-8
    username: root
    password: petropolis
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      hdbm2ddl:
        create_namespaces: true
        auto: update
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: true

openai:
  api:
    url: https://api.openai-proxy.org/v1/chat/completions
    key: sk-jVfmC9s3HLlOzUPCu6H7wPbtsM73as58PEnV1iYjCJgJvif9
    modelType: gpt-4o